#160577594 Enable users to see their article stats
andela/ah-codeblooded-frontend pull request #35
Opened 2018-11-21 19:47 UTC by mutaimwiti

**What does this PR do?**

This PR adds functionality that allows users to see how their articles are performing on the platform on a single dashboard.

**Description of Task to be completed?**

The article stats data gives the user data about the performance of their articles. Only the owner is able to see this data. This means that one has to be logged in to view their reading stats.

**How should this be manually tested?**

This feature can be manually tested by opening this PR's review app.
1. Log in to the app.
2. Add `/article-stats` to the address bar and hit enter. You should be taken to a page that displays your article stats.

**What are the relevant pivotal tracker stories?**

[#160577594](https://www.pivotaltracker.com/story/show/160577594)

**Screenshots**
Below is WIP image showing a rough idea of the direction we are headed
<img width="612" alt="screen shot 2018-11-21 at 22 44 12" src="https://user-images.githubusercontent.com/8180548/48864921-1cb64f80-eddf-11e8-9839-357ec2dfcdd0.png">

2018-11-23 09:35 UTC, C3real-kill3r approved these changes

2018-11-23 09:39 UTC, YAHYA-H approved these changes

2018-11-25 20:58 UTC, gitaumoses4 requested changes
Good work on the task so far. 
*Stats Refreshing Recommendation*
I would advice when the data is refreshing you could use the navigation bar loader which would be more user friendly since it allows the user to continue exploring the page as the new data is being loaded.

2018-11-26 23:41 UTC, gitaumoses4 commented
Hello @mutaimwiti did you implement the refreshing?

2018-11-27 04:17 UTC, mutaimwiti commented
> Hello @mutaimwiti did you implement the refreshing?

Not yet @gitaumoses4 I will be doing that today.

2018-11-27 20:43 UTC, mutaimwiti commented
> Hello @mutaimwiti did you implement the refreshing?

It is now done @gitaumoses4

2018-11-29 05:42 UTC, paulrimiru reviewed
Good work

2018-11-29 05:42 UTC, PaulKariukiRimiru commented on src/containers/Stats/state/actions.js
> +// refresh stats
REmove inline comment

2018-11-29 05:52 UTC, gitaumoses4 approved these changes

2018-11-29 07:43 UTC, merged