#162199777 Handle 404 error (Page Not Found)
andela/ah-codeblooded-frontend pull request #45
Opened 2018-11-28 07:03 UTC by bevkololi

**What does this PR do?**

It handles the 404 or Page Not found error

**Description of Task to be completed?**

Whenever a user tries to access an undefined route, he or she is redirected to this specific page.

**How should this be manually tested?**

- Open this PR's review app
- Manoeuvre to any route of your choosing
- Edit route to a different one that does not exists
- You should see an Error Page

**Any background context you want to provide?**

N/A

**What are the relevant pivotal tracker stories?**

https://www.pivotaltracker.com/n/projects/2198535/stories/162199777

**Screenshots (if appropriate)**
Screenshot when someone tries to visit an undefined route

<img width="1440" alt="screen shot 2018-11-28 at 09 48 35" src="https://user-images.githubusercontent.com/26184534/49134387-6a0d5200-f2f4-11e8-83bb-1a29906037d3.png">

**Questions:**

N/A

2018-11-28 15:18 UTC, YAHYA-H approved these changes
LOOK GOOD ! 👍

2018-11-29 12:35 UTC, C3real-kill3r approved these changes

2018-11-29 13:27 UTC, paulrimiru requested changes
Fix that one issue and we can merge it

2018-11-29 13:27 UTC, paulrimiru commented on src/pages/Error404Page/Error404Page.test.js
> +describe('<PageNotFound> component', () => {
Please refactor this title

2018-11-29 14:14 UTC, bevkololi commented on src/pages/Error404Page/Error404Page.test.js
> +describe('<PageNotFound> component', () => {
Done @PaulKariukiRimiru

2018-11-29 19:02 UTC, paulrimiru approved these changes

2018-11-29 19:03 UTC, merged